---
new_page_extension: md
auto_deploy: true
admin_path: admin/
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - parliament-vote
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _parliamentterms
  label: Parliament Terms
  create: documents
  match: "**"
  new_doc_ext: md
  templates:
  - parliament-term
- type: directory
  path: _parliamentvotes
  label: Parliament Votes
  create: documents
  match: "**"
  new_doc_ext: md
  templates:
  - parliament-vote
- type: directory
  path: _minemen
  label: Minemen
  create: documents
  match: "**"
  templates:
  - mineman
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
